Refactor deploy script
Incorporate suggestions from @muness (including automated
installation of pygments when it is not yet installed).

diff --git a/tasks/deploy b/tasks/deploy
--- a/tasks/deploy
+++ b/tasks/deploy
@@ -6,19 +6,8 @@ function tag_deployment {
   git tag -a -m "Tagging deployment at $CURRENT_TIMESTAMP" $TAG_NAME
 }
 
-function check_for_pygments {
-  echo "Checking for pygments"
-  port installed | grep "py25-pygments"
+function verify_or_install_pygments {
+  (port installed | grep "py25-pygments") || (echo "Missing pygments. Installing it..." && sudo port install py25-pygments)
 }
 
-function confirm_prerequisites_or_exit {
-  echo "Checking for prerequisites"
-
-  check_for_pygments
-  if [[ $? -ne "0" ]]; then
-    echo "You must first install pygments via MacPorts"
-    exit 1
-  fi
-}
-
-confirm_prerequisites_or_exit && jekyll && rsync -avz --delete _site/ jasonrudolph.com:jasonrudolph.com && tag_deployment
+verify_or_install_pygments && jekyll && rsync -avz --delete _site/ jasonrudolph.com:jasonrudolph.com && tag_deployment
